title: 완두블로그

email: hi@wani.kr

markdown: kramdown

permalink: /posts/:year/:month/:day/:title/
paginate_path: /posts/page/:num

paginate: 10

plugins:
  - jekyll-paginate

author:
  twitter: wan2land
  github: wan2land

sass:
  sass_dir: _scss
  style: compressed
